import { IconInfo } from '.';

const w: IconInfo[] = [
  {
    qweather: 'warnings-1001',
    label: '台风',
    caiyun: 'warnings-01',
  },
  { qweather: 'warnings-1002', label: '龙卷风' },
  {
    qweather: 'warnings-1003',
    label: '暴雨',
    caiyun: 'warnings-02',
  },
  {
    qweather: 'warnings-1004',
    label: '暴雪',
    caiyun: 'warnings-03',
  },
  {
    qweather: 'warnings-1005',
    label: '寒潮',
    caiyun: 'warnings-04',
  },
  {
    qweather: 'warnings-1006',
    label: '大风',
    caiyun: 'warnings-05',
  },
  {
    qweather: 'warnings-1007',
    label: '沙尘暴',
    caiyun: 'warnings-06',
  },
  { qweather: 'warnings-1008', label: '低温冻害' },
  {
    qweather: 'warnings-1009',
    label: '高温',
    caiyun: 'warnings-07',
  },
  { qweather: 'warnings-1010', label: '热浪' },
  { qweather: 'warnings-1011', label: '干热风' },
  { qweather: 'warnings-1012', label: '下击暴流' },
  { qweather: 'warnings-1013', label: '雪崩' },
  {
    qweather: 'warnings-1014',
    label: '雷电',
    caiyun: 'warnings-09',
  },
  {
    qweather: 'warnings-1015',
    label: '冰雹',
    caiyun: 'warnings-10',
  },
  {
    qweather: 'warnings-1016',
    label: '霜冻',
    caiyun: 'warnings-11',
  },
  {
    qweather: 'warnings-1017',
    label: '大雾',
    caiyun: 'warnings-12',
  },
  { qweather: 'warnings-1018', label: '低空风切变' },
  {
    qweather: 'warnings-1019',
    label: '霾',
    caiyun: 'warnings-13',
  },
  {
    qweather: 'warnings-1020',
    label: '雷雨大风',
    caiyun: 'warnings-16',
  },
  {
    qweather: 'warnings-1021',
    label: '道路结冰',
    caiyun: 'warnings-14',
  },
  {
    qweather: 'warnings-1022',
    label: '干旱',
    caiyun: 'warnings-08',
  },
  { qweather: 'warnings-1023', label: '海上大风' },
  { qweather: 'warnings-1024', label: '高温中暑' },
  {
    qweather: 'warnings-1025',
    label: '森林火险',
    caiyun: 'warnings-15',
  },
  { qweather: 'warnings-1026', label: '草原火险' },
  { qweather: 'warnings-1027', label: '冰冻' },
  { qweather: 'warnings-1028', label: '空间天气' },
  { qweather: 'warnings-1029', label: '重污染' },
  { qweather: 'warnings-1030', label: '低温雨雪冰冻' },
  { qweather: 'warnings-1031', label: '强对流' },
  { qweather: 'warnings-1032', label: '臭氧' },
  { qweather: 'warnings-1033', label: '大雪' },
  { qweather: 'warnings-1034', label: '寒冷' },
  { qweather: 'warnings-1035', label: '连阴雨' },
  { qweather: 'warnings-1036', label: '渍涝风险' },
  { qweather: 'warnings-1037', label: '地质灾害气象风险' },
  { qweather: 'warnings-1038', label: '强降雨' },
  { qweather: 'warnings-1039', label: '强降温' },
  { qweather: 'warnings-1040', label: '雪灾' },
  { qweather: 'warnings-1041', label: '森林（草原）火险' },
  { qweather: 'warnings-1042', label: '医疗气象' },
  { qweather: 'warnings-1043', label: '雷暴' },
  { qweather: 'warnings-1044', label: '停课信号' },
  { qweather: 'warnings-1045', label: '停工信号' },
  { qweather: 'warnings-1046', label: '海上风险' },
  {
    qweather: 'warnings-1047',
    label: '春季沙尘天气',
    caiyun: 'warnings-17',
  },
  { qweather: 'warnings-1048', label: '降温' },
  { qweather: 'warnings-1049', label: '台风暴雨' },
  { qweather: 'warnings-1050', label: '严寒' },
  {
    qweather: 'warnings-1051',
    label: '沙尘',
    caiyun: 'warnings-18',
  },
  { qweather: 'warnings-1052', label: '海上雷雨大风' },
  { qweather: 'warnings-1053', label: '海上大雾' },
  { qweather: 'warnings-1054', label: '海上雷电' },
  { qweather: 'warnings-1055', label: '海上台风' },
  { qweather: 'warnings-1056', label: '低温' },
  {
    qweather: 'warnings-1057',
    label: '道路冰雪',
  },
  { qweather: 'warnings-1058', label: '雷暴大风' },
  { qweather: 'warnings-1059', label: '持续低温' },
  // { qweather: 'warnings-1060', label: '能见度不良' },
  { qweather: 'warnings-1061', label: '浓浮沉' },
  // { qweather: 'warnings-1062', label: '海区大风' },
  // { qweather: 'warnings-1063', label: '短历时强降水' },
  { qweather: 'warnings-1064', label: '短时强降雨' },
  // { qweather: 'warnings-1065', label: '海区大雾' },
  // { qweather: 'warnings-1066', label: '中暑气象条件' },
  // { qweather: 'warnings-1067', label: '重污染天气' },
  // { qweather: 'warnings-1068', label: '一氧化碳中毒气象条件' },
  // { qweather: 'warnings-1069', label: '感冒等呼吸道疾病气象条件' },
  // { qweather: 'warnings-1071', label: '腹泻等肠道疾病气象条件' },
  // { qweather: 'warnings-1072', label: '心脑血管疾病气象条件' },
  // { qweather: 'warnings-1073', label: '洪涝灾害气象风险' },
  // { qweather: 'warnings-1074', label: '重污染气象条件' },
  // { qweather: 'warnings-1075', label: '城市内涝气象风险' },
  // { qweather: 'warnings-1076', label: '洪水灾害气象风险' },
  // { qweather: 'warnings-1077', label: '森林火险气象风险' },
  // { qweather: 'warnings-1078', label: '气象干旱' },
  // { qweather: 'warnings-1079', label: '农业气象风险' },
  // { qweather: 'warnings-1080', label: '强季风' },
  // { qweather: 'warnings-1081', label: '电线积冰' },
  // { qweather: 'warnings-1082', label: '脑卒中气象风险' },
  // { qweather: 'warnings-1084', label: '森林（草原）火灾气象风险' },
  // { qweather: 'warnings-1085', label: '雷雨强风' },
  // { qweather: 'warnings-1086', label: '低温凝冻' },
  // { qweather: 'warnings-1087', label: '低温冷害' },
  // { qweather: 'warnings-1088', label: '全国农业气象灾害风险' },
  // { qweather: 'warnings-1089', label: '冬小麦干热风灾害风险预警' },
  { qweather: 'warnings-1101', label: '洪水' },
  { qweather: 'warnings-1302', label: '泥石流' },
  { qweather: 'warnings-1402', label: '风暴潮' },
  { qweather: 'warnings-1601', label: '炎热' },
  { qweather: 'warnings-1602', label: '强烈季风信号' },
  { qweather: 'warnings-1603', label: '山泥倾泻' },
  { qweather: 'warnings-1604', label: '热带气旋' },
  { qweather: 'warnings-1605', label: '火灾危险' },
  {
    qweather: 'warnings-1606',
    label: '新界北部水浸特别报告',
  },
  { qweather: 'warnings-1607', label: '寒冷天气' },
  // { qweather: 'warnings-1701', label: '低温特报' },
  // { qweather: 'warnings-1702', label: '陆上强风' },
  // { qweather: 'warnings-1703', label: '降雨特报' },
  { qweather: 'warnings-2001', label: '大风' },
  { qweather: 'warnings-2002', label: '强降雪和结冰' },
  { qweather: 'warnings-2003', label: '大雾' },
  { qweather: 'warnings-2004', label: '海岸风险' },
  { qweather: 'warnings-2005', label: '森林火险' },
  { qweather: 'warnings-2006', label: '雨' },
  { qweather: 'warnings-2007', label: '大雨洪水' },
  { qweather: 'warnings-2008', label: '冻雨和结冰' },
  { qweather: 'warnings-2009', label: '地面霜' },
  { qweather: 'warnings-2010', label: '扬尘风' },
  { qweather: 'warnings-2011', label: '强地面风' },
  { qweather: 'warnings-2012', label: '炎热' },
  { qweather: 'warnings-2013', label: '夜间炎热' },
  { qweather: 'warnings-2014', label: '寒冷' },
  { qweather: 'warnings-2015', label: '雷暴和闪电' },
  { qweather: 'warnings-2016', label: '冰雹风暴' },
  { qweather: 'warnings-2017', label: '海况风险' },
  { qweather: 'warnings-2018', label: '渔业风险' },
  { qweather: 'warnings-2019', label: '低湿度' },
  { qweather: 'warnings-2020', label: '累计降水风险' },
  { qweather: 'warnings-2021', label: '冲浪风险' },
  { qweather: 'warnings-2022', label: '海上大风' },
  { qweather: 'warnings-2023', label: '道路天气风险' },
  { qweather: 'warnings-2024', label: '雷雨' },
  { qweather: 'warnings-2025', label: '雷雨大雾' },
  { qweather: 'warnings-2026', label: '破坏性大风' },
  { qweather: 'warnings-2027', label: '草原火灾条件' },
  { qweather: 'warnings-2028', label: '天气预警建议' },
  { qweather: 'warnings-2052', label: '大雪' },
  // { qweather: 'warnings-2053', label: 'Zonda Wind' },
  // { qweather: 'warnings-2054', label: '风暴' },
  // { qweather: 'warnings-9998', label: '天气预警' },
  { qweather: 'warnings-9999', label: '其他' },
];

export default w;
