import { IconInfo } from '.';

const w: IconInfo[] = [
  { qweather: '1', label: '优', caiyun: '1' },
  { qweather: '2', label: '良', caiyun: '2' },
  { qweather: '3', label: '轻度污染', caiyun: '3' },
  { qweather: '4', label: '中度污染', caiyun: '4' },
  { qweather: '5', label: '重度污染', caiyun: '5' },
  { qweather: '6', label: '严重污染', caiyun: '6' },
  { qweather: '100', label: '晴', caiyun: 'CLEAR_DAY' },
  {
    qweather: '101',
    label: '多云',
    caiyun: 'PARTLY_CLOUDY_DAY',
  },
  { qweather: '102', label: '少云' },
  { qweather: '103', label: '晴间多云' },
  { qweather: '104', label: '阴', caiyun: 'CLOUDY' },
  { qweather: '150', label: '晴', caiyun: 'CLEAR_NIGHT' },
  {
    qweather: '151',
    label: '多云',
    caiyun: 'PARTLY_CLOUDY_NIGHT',
  },
  { qweather: '152', label: '少云' },
  { qweather: '153', label: '晴间多云' },
  { qweather: '300', label: '阵雨' },
  { qweather: '301', label: '强阵雨' },
  { qweather: '302', label: '雷阵雨' },
  { qweather: '303', label: '强雷阵雨' },
  { qweather: '304', label: '雷阵雨伴有冰雹' },
  { qweather: '305', label: '小雨', caiyun: 'LIGHT_RAIN' },
  {
    qweather: '306',
    label: '中雨',
    caiyun: 'MODERATE_RAIN',
  },
  { qweather: '307', label: '大雨', caiyun: 'HEAVY_RAIN' },
  { qweather: '308', label: '极端降雨' },
  { qweather: '309', label: '毛毛雨/细雨' },
  { qweather: '310', label: '暴雨', caiyun: 'STORM_RAIN' },
  { qweather: '311', label: '大暴雨' },
  { qweather: '312', label: '特大暴雨' },
  { qweather: '313', label: '冻雨' },
  { qweather: '314', label: '小到中雨' },
  { qweather: '315', label: '中到大雨' },
  { qweather: '316', label: '大到暴雨' },
  { qweather: '317', label: '暴雨到大暴雨' },
  { qweather: '318', label: '大暴雨到特大暴雨' },
  { qweather: '350', label: '阵雨' },
  { qweather: '351', label: '强阵雨' },
  { qweather: '399', label: '雨' },
  { qweather: '400', label: '小雪', caiyun: 'LIGHT_SNOW' },
  {
    qweather: '401',
    label: '中雪',
    caiyun: 'MODERATE_SNOW',
  },
  { qweather: '402', label: '大雪', caiyun: 'HEAVY_SNOW' },
  { qweather: '403', label: '暴雪', caiyun: 'STORM_SNOW' },
  { qweather: '404', label: '雨夹雪' },
  { qweather: '405', label: '雨雪天气' },
  { qweather: '406', label: '阵雨夹雪' },
  { qweather: '407', label: '阵雪' },
  { qweather: '408', label: '小到中雪' },
  { qweather: '409', label: '中到大雪' },
  { qweather: '410', label: '大到暴雪' },
  { qweather: '456', label: '阵雨夹雪' },
  { qweather: '457', label: '阵雪' },
  { qweather: '499', label: '雪' },
  { qweather: '500', label: '薄雾' },
  { qweather: '501', label: '雾', caiyun: 'FOG' },
  { qweather: '502', label: '霾', caiyun: 'LIGHT_HAZE' },
  { qweather: '503', label: '扬沙' },
  { qweather: '504', label: '浮尘', caiyun: 'DUST' },
  { qweather: '507', label: '沙尘暴', caiyun: 'SAND' },
  { qweather: '508', label: '强沙尘暴' },
  { qweather: '509', label: '浓雾' },
  { qweather: '510', label: '强浓雾' },
  {
    qweather: '511',
    label: '中度霾',
    caiyun: 'MODERATE_HAZE',
  },
  {
    qweather: '512',
    label: '重度霾',
    caiyun: 'HEAVY_HAZE',
  },
  { qweather: '513', label: '严重霾' },
  { qweather: '514', label: '大雾' },
  { qweather: '515', label: '特强浓雾' },
  { qweather: '900', label: '热' },
  { qweather: '901', label: '冷' },
  { qweather: '999', label: '未知' },
  { label: '大风', caiyun: 'WIND' },
];

export default w;
